### ISSUE TITLE
shfmt is returning errors in logs and not annotating files

### ISSUE THREAD

**Issue by dprotaso** [knative/actions#127]
From: https://github.com/knative-sandbox/net-contour/actions/runs/4536017599/jobs/7992187078?pr=890

> reviewdog: This GitHub token doesn't have write permission of Review API [1], 
> so reviewdog will report results via logging command [2] and create annotations similar to
> github-pr-check reporter as a fallback.
> [1]: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target, 
> [2]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands

**Comment by dprotaso** [comment]
ALso not sure if the workflows in suggestor are meant to block

**Comment by kvmware** [comment]
Hard to test this one because of the permssions between my local fork and other repos. However, i believe reviewdog uses the local report so https://github.com/knative/actions/pull/128 this should change the reporter so that `shfmt` shows up it is strange how shellcheck suggester was showing up but not `shfmt` :shrug:. The naming is a little weird the suggestor workflow although the steps have different names that would be more self-explainable the check only shows `shell/ suggestor` which in reality there is the suggestion, shfmt, and finally the actual lint that is being done. So, yes it was a valid failure. However, the scope is file wide which we discussed about in prod WG meeting to switch back to just the actual changes, but the problem with that is hacks etc will never be cleaned up. So, the idea is if someone is making changes to a file they should do a good deed and shellcheck and fix the whole file they are working on so that we can have more secure shell scripts. The ramification of this is that automation like this will fail because it is changing a file that needs to be shellchecked but owned by a bot in whichcase a override is needed. Open to suggestions.

**Comment by kvmware** [comment]
Looks like the changes worked for now https://github.com/knative-sandbox/net-contour/actions/runs/4536017599

Still seeing the reviewdog defaulting back to github-pr-check and will try to keep an eye out for that on other repos.

**Comment by kvmware** [comment]
This has been fixed by my and Mahamed's changes
